### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by codelover1226** [10YearsOfGoodLuckIfYouFollow/RustBinaryStream#1]
If you making brutal history in github, github will suspend your profile.
Take care.

**Comment by codelover1226** [comment]
Please reply

**Comment by codelover1226** [comment]
don't follow other users as fast.
Github can close your account

**Comment by 10YearsOfGoodLuckIfYouFollow** [comment]
> don't follow other users as fast. Github can close your account

how fast do you suggest me there are people with over 200k follows?

**Comment by codelover1226** [comment]
I am not sure.
